name = "lean-value-theorem"
version = "0.1.0"
defaultTargets = ["lean-value-theorem"]
keywords = ["math"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
linter.unusedVariables = false
maxSynthPendingDepth = 3

[[lean_lib]]
name = "LeanValueTheorem"

[[lean_exe]]
name = "lean-value-theorem"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
